inlets-pro:
  tokenSecretName: mysql-customer2-token
  ingress:
    domain: mysql-customer2.inletscd.welteki.dev

  dataPlane:
    type: ClusterIP
    ports:
    - targetPort: 3306
      protocol: TCP
      name: mysql
      port: 3306
