inlets-pro:
  tokenSecretName: postgresql-customer1-token
  ingress:
    domain: postgresql-customer1.inletscd.welteki.dev

  dataPlane:
    type: ClusterIP
    ports:
    - targetPort: 5432
      protocol: TCP
      name: postgresql
      port: 5432
