apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: inlets-tunnel
spec:
  generators:
  - list:
      elements:
      - name: postgresql-customer1-tunnel
        valuesFile: values-postgresql-customer1.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        chart: inlets
        repoURL: https://github.com/welteki/inlets-server-argocd-demo.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - '{{valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          selfHeal: true